services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  grafana:
    image: grafana/grafana:9.5.0
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
